### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by wighawag** [rixo/svelte-loader-hot#3] opened 2020-04-03 17:30 UTC
I just switched from svelte-loader to svelte-loader-hot and in my webpack config I set up svelte-loader with the preprocess option to parse some tailwind css syntax.

The preprocess works with svelte-loader but fails with svelte-loader-hot

When I remove the specific tailwind css syntax, svelte-loader-hot works and hot reload.

Is there a change in the preprocess option from svelte-loader to svelte-loader-hot ?

**Comment by rixo** [comment] 2020-04-03 20:15
No, it should work the same. Looks like a bug, I'll try to see if I can reproduce. Any chance you can share your webpack config?

Have you tried with `svelte-loader-hot`, but the `hot` option set to false? Same result?

**Comment by wighawag** [comment] 2020-04-04 10:19
Here is the commit that I use to test svelte-loader-hot : https://github.com/wighawag/eip-2585/commit/22f62816bde2dd59b186af6c5d17d640197828a3

for hot option you means the `hotReload` option ?

If so it still has the same issue

**Comment by rixo** [comment] 2020-04-04 16:09
Hmm, I tried to add `svelte-preprocess` to my [sapper template example](https://github.com/rixo/sapper-template-hot/tree/webpack) and it seems to work.

In your project, you're missing the `preprocess` option in the client part of the config ([here](https://github.com/wighawag/eip-2585/blob/22f62816bde2dd59b186af6c5d17d640197828a3/webapp/webpack.config.js#L48)). It's probably needed there too.

If this doesn't help, can you share the error you're getting?

**Comment by rixo** [comment] 2020-04-04 16:19
And yes, I meant the `hotReload` option sorry. Got confused with the Rollup plugin...

**Comment by wighawag** [comment] 2020-04-04 16:34
Yes, you right, it works : https://github.com/wighawag/eip-2585/commit/1d95abdea08e294db0a67119e4d1c5fa0d0724e1

Thanks!

I guess the preprocess was not needed in **non**-hot-reload mode because the css get generated once by the server and it never need to be generated again client side.
But with hot-reload it now need to be handled by client side for hot reload to work 

The only issue I have now is that when I remove some css class definition, the css does not get updated, but if I change the value in the class definition, it get applied.

Not sure if this is solvable ?

**Comment by rixo** [comment] 2020-04-04 23:09
I'm somewhat surprised that it works without the preprocess in the client, even with the official plugin. I don't know enough about tailwind and postcss to speculate as to why... But glad to hear you could make it work!

And yes, CSS is still badly supported. Simply put, Svelte adds some stylesheets to the document, and they are never removed. So when you change something, the change is visible (same CSS specificity, last appended stylesheet wins). But when you remove a CSS rule, it stays there forever...

Said like that it makes me realize that it is probably a sizable memory leak too (until you reload the page).

I have added a fix for this. Can you try with `svelte-loader-hot@next` (you should get 0.3.1-0), and see if it works better for you?

**Comment by wighawag** [comment] 2020-04-17 10:13
Yes seems like it works better. Could not test all the thing but I saw css update going through even when pre processed

**Comment by rixo** [comment] 2020-05-20 23:34
I think we're done here. Feel free to reopen if needed.

**Closed by rixo** 2020-05-20 23:34 UTC
Labels: bug
